// SPDX-License-Identifier: EUPL-1.2

package server

import (
	"context"
	"crypto/sha1"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	core "dappco.re/go"
	"dappco.re/go/forge"
)

// probeForgeAuth performs a direct net/http call to /api/v1/user with the
// token in the Authorization: Bearer header. Mirrors what go-forge does
// internally so a probe failure here implies a real auth problem (not a
// go-forge wiring quirk). Returns the authenticated user's login on
// success.
func probeForgeAuth(ctx context.Context, base, token string) (string, error) {
	c, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(c, http.MethodGet, base+"/api/v1/user", nil)
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+token)
	req.Header.Set("Accept", "application/json")
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return "", err
	}
	defer func() { _ = resp.Body.Close() }()
	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode >= 400 {
		return "", fmt.Errorf("HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(body)))
	}
	var user struct {
		Login string `json:"login"`
	}
	if err := json.Unmarshal(body, &user); err != nil {
		return "", err
	}
	return user.Login, nil
}

// forge_* bridge tools surface the canonical core/go-forge Forgejo client.
// Token resolution: ~/.claude/secrets/forge_token (single-line) | env
// FORGE_TOKEN | core config "forge.token". Base URL: env FORGE_URL or
// "https://forge.lthn.sh" (Snider's homelab — adjust per machine).

var (
	forgeOnce   sync.Once
	forgeClient *forge.Forge
	forgeBase   string
	forgeOk     bool
)

func (b *MCPBridge) forgeService() (*forge.Forge, bool) {
	forgeOnce.Do(func() {
		token := readForgeToken()
		if strings.TrimSpace(token) == "" {
			return
		}
		base := os.Getenv("FORGE_URL")
		if base == "" {
			base = "https://forge.lthn.sh"
		}
		forgeBase = base
		forgeClient = forge.NewForge(base, token)
		forgeOk = true
		// Light diagnostic so the dev sees the token-source + length without
		// printing the secret. Useful when 401s happen and the user wonders
		// which path won the resolver. Prefix only — never log the full
		// token. Sha1 prefix lets a developer cross-check against forgejo's
		// "access token does not exist [sha: …]" error message.
		prefix := token
		if len(prefix) > 6 {
			prefix = prefix[:6]
		}
		sum := sha1.Sum([]byte(token))
		hash := hex.EncodeToString(sum[:])
		core.Print(core.Stderr(), "ide.server.forge: base=%s token_len=%d prefix=%s sha1=%s\n", base, len(token), prefix, hash)
	})
	return forgeClient, forgeOk
}

func readForgeToken() string {
	if t := strings.TrimSpace(os.Getenv("FORGE_TOKEN")); t != "" {
		return t
	}
	home, err := os.UserHomeDir()
	if err == nil {
		paths := []string{
			filepath.Join(home, ".claude", "secrets", "forge_token"),
			filepath.Join(home, ".core", "secrets", "forge_token"),
		}
		for _, p := range paths {
			data, err := os.ReadFile(p)
			if err == nil {
				// Strip ALL whitespace including embedded \r and \n the
				// file might contain when generated by tools that wrap
				// the token across lines.
				out := strings.Map(func(r rune) rune {
					switch r {
					case ' ', '\t', '\n', '\r', 0:
						return -1
					}
					return r
				}, string(data))
				if out != "" {
					return out
				}
			}
		}
	}
	return ""
}

// toolForgeStatus reports whether a forge client could be initialised + the
// resolved base URL. Probes /api/v1/user with the loaded token via net/http
// directly so the panel surfaces a clean "configured & valid" vs "configured
// but rejected" distinction (the latter usually means an expired/revoked
// token).
func (b *MCPBridge) toolForgeStatus(ctx context.Context, _ map[string]any) map[string]any {
	_, ok := b.forgeService()
	hint := ""
	authed := false
	authedAs := ""
	if !ok {
		hint = "no token found — set FORGE_TOKEN env, or write a token to ~/.claude/secrets/forge_token"
	} else {
		token := readForgeToken()
		// Direct probe via net/http with both header forms (Forgejo accepts
		// either; we use Bearer to match go-forge's emit shape).
		login, err := probeForgeAuth(ctx, forgeBase, token)
		if err == nil && login != "" {
			authed = true
			authedAs = login
		} else if err != nil {
			hint = "token rejected by " + forgeBase + ": " + err.Error()
		}
	}
	return map[string]any{
		"ok": true,
		"value": map[string]any{
			"configured":   ok,
			"authenticated": authed,
			"as":           authedAs,
			"base":         forgeBase,
			"hint":         hint,
		},
	}
}

// toolForgeOrgs lists orgs the authenticated user belongs to. Snider's
// account spans `core` (homelab canon), `lthn` (network), `agent` etc.
func (b *MCPBridge) toolForgeOrgs(ctx context.Context, _ map[string]any) map[string]any {
	f, ok := b.forgeService()
	if !ok {
		return errResp("forge client not configured")
	}
	orgs, err := f.Orgs.ListOrgs(ctx)
	if err != nil {
		return map[string]any{"ok": false, "error": err.Error()}
	}
	out := make([]map[string]any, 0, len(orgs))
	for _, o := range orgs {
		out = append(out, map[string]any{
			"name":        o.Name,
			"full_name":   o.FullName,
			"description": o.Description,
			"website":     o.Website,
			"avatar":      o.AvatarURL,
		})
	}
	return map[string]any{"ok": true, "value": map[string]any{"orgs": out, "count": len(out)}}
}

// toolForgeRepos lists repos for an org (or the authenticated user when
// org is empty). Returns name/full_name/description/private/fork/stars.
func (b *MCPBridge) toolForgeRepos(ctx context.Context, params map[string]any) map[string]any {
	f, ok := b.forgeService()
	if !ok {
		return errResp("forge client not configured")
	}
	org := paramString(params, "org", "")
	var repos []forgeRepo
	if org == "" {
		raw, err := f.Repos.ListUserRepos(ctx)
		if err != nil {
			return map[string]any{"ok": false, "error": err.Error()}
		}
		for _, r := range raw {
			repos = append(repos, repoToInfo(r))
		}
	} else {
		raw, err := f.Repos.ListOrgRepos(ctx, org)
		if err != nil {
			return map[string]any{"ok": false, "error": err.Error()}
		}
		for _, r := range raw {
			repos = append(repos, repoToInfo(r))
		}
	}
	out := make([]map[string]any, 0, len(repos))
	for _, r := range repos {
		out = append(out, map[string]any{
			"name":        r.Name,
			"full_name":   r.FullName,
			"description": r.Description,
			"private":     r.Private,
			"fork":        r.Fork,
			"stars":       r.Stars,
			"updated_at":  r.UpdatedAt,
			"html_url":    r.HTMLURL,
		})
	}
	return map[string]any{"ok": true, "value": map[string]any{"repos": out, "count": len(out)}}
}

// toolForgeIssues lists issues for a given owner/repo. State filter
// optional ("open" | "closed" | "all" — default "open").
func (b *MCPBridge) toolForgeIssues(ctx context.Context, params map[string]any) map[string]any {
	f, ok := b.forgeService()
	if !ok {
		return errResp("forge client not configured")
	}
	owner := paramString(params, "owner", "")
	repo := paramString(params, "repo", "")
	if owner == "" || repo == "" {
		return errResp("owner + repo required")
	}
	issues, err := f.Issues.ListRepoIssues(ctx, owner, repo)
	if err != nil {
		return map[string]any{"ok": false, "error": err.Error()}
	}
	out := make([]map[string]any, 0, len(issues))
	for _, i := range issues {
		// PR-shaped issues have PullRequest field set; skip those (covered
		// by toolForgePulls)
		if i.PullRequest != nil {
			continue
		}
		out = append(out, map[string]any{
			"number":     i.Index,
			"title":      i.Title,
			"state":      i.State,
			"comments":   i.Comments,
			"updated_at": i.Updated,
			"html_url":   i.HTMLURL,
			"author":     userLogin(i.User),
		})
	}
	return map[string]any{"ok": true, "value": map[string]any{"issues": out, "count": len(out)}}
}

// toolForgePulls lists PRs for a repo.
func (b *MCPBridge) toolForgePulls(ctx context.Context, params map[string]any) map[string]any {
	f, ok := b.forgeService()
	if !ok {
		return errResp("forge client not configured")
	}
	owner := paramString(params, "owner", "")
	repo := paramString(params, "repo", "")
	if owner == "" || repo == "" {
		return errResp("owner + repo required")
	}
	pulls, err := f.Pulls.ListPullRequests(ctx, owner, repo)
	if err != nil {
		return map[string]any{"ok": false, "error": err.Error()}
	}
	out := make([]map[string]any, 0, len(pulls))
	for _, p := range pulls {
		out = append(out, map[string]any{
			"number":     p.Index,
			"title":      p.Title,
			"state":      p.State,
			"merged":     p.HasMerged,
			"draft":      p.Draft,
			"updated_at": p.Updated,
			"html_url":   p.HTMLURL,
			"author":     userLogin(p.User),
			"base":       p.Base.Ref,
			"head":       p.Head.Ref,
		})
	}
	return map[string]any{"ok": true, "value": map[string]any{"pulls": out, "count": len(out)}}
}

// toolForgeReleases lists recent releases AND tags for a single owner/repo.
// Forge.lthn.sh repos commonly use tags without an explicit GitHub-style
// "release" — so we surface both, merged + sorted by recency. Calls the
// API directly (go-forge's Releases service exists but no TagService yet).
func (b *MCPBridge) toolForgeReleases(ctx context.Context, params map[string]any) map[string]any {
	owner := strings.TrimSpace(paramString(params, "owner", ""))
	repo := strings.TrimSpace(paramString(params, "repo", ""))
	if owner == "" || repo == "" {
		return map[string]any{"ok": false, "error": "owner and repo required"}
	}
	limit := paramInt(params, "limit", 20)
	if limit <= 0 || limit > 100 {
		limit = 20
	}

	out := make([]map[string]any, 0, limit)

	// Try Releases first (explicit releases trump tags when present)
	if f, ok := b.forgeService(); ok {
		page, err := f.Releases.ListReleasesPage(ctx, owner, repo, forge.ListOptions{Page: 1, PageSize: limit})
		if err == nil {
			for _, r := range page.Items {
				out = append(out, map[string]any{
					"kind":         "release",
					"name":         r.TagName,
					"title":        r.Title,
					"target":       r.Target,
					"draft":        r.IsDraft,
					"prerelease":   r.IsPrerelease,
					"published_at": r.PublishedAt.UTC().Format(time.RFC3339),
					"html_url":     r.HTMLURL,
					"tarball_url":  r.TarURL,
					"author":       userLogin(r.Author),
				})
			}
		}
	}

	// Always merge in tags too — Forge repos often only have tags.
	tagURL := strings.TrimSuffix(forgeBaseURL(), "/") + "/api/v1/repos/" + owner + "/" + repo + "/tags?limit=" + fmt.Sprintf("%d", limit)
	if tagBody := forgeAuthedGET(tagURL); tagBody != nil {
		var tags []struct {
			Name        string `json:"name"`
			Message     string `json:"message"`
			ID          string `json:"id"`
			ZipballURL  string `json:"zipball_url"`
			TarballURL  string `json:"tarball_url"`
			Commit      struct {
				URL     string `json:"url"`
				SHA     string `json:"sha"`
				Created string `json:"created"`
			} `json:"commit"`
		}
		if err := json.Unmarshal(tagBody, &tags); err == nil {
			seen := map[string]bool{}
			for _, e := range out {
				seen[asString(e["name"])] = true
			}
			for _, t := range tags {
				if seen[t.Name] {
					continue
				}
				out = append(out, map[string]any{
					"kind":         "tag",
					"name":         t.Name,
					"title":        t.Message,
					"target":       t.Commit.SHA,
					"published_at": t.Commit.Created,
					"tarball_url":  t.TarballURL,
					"zipball_url":  t.ZipballURL,
					"html_url":     "https://forge.lthn.sh/" + owner + "/" + repo + "/src/tag/" + t.Name,
				})
			}
		}
	}

	// Sort by published_at desc; cap to limit
	sort.Slice(out, func(i, j int) bool {
		return asString(out[i]["published_at"]) > asString(out[j]["published_at"])
	})
	if len(out) > limit {
		out = out[:limit]
	}

	return map[string]any{
		"ok": true,
		"value": map[string]any{
			"releases": out,
			"count":    len(out),
			"owner":    owner,
			"repo":     repo,
		},
	}
}

func forgeBaseURL() string {
	if v := strings.TrimSpace(os.Getenv("FORGE_URL")); v != "" {
		return v
	}
	return "https://forge.lthn.sh"
}

func forgeAuthedGET(url string) []byte {
	tok := readForgeToken()
	if tok == "" {
		return nil
	}
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return nil
	}
	req.Header.Set("Authorization", "token "+tok)
	req.Header.Set("Accept", "application/json")
	resp, err := (&http.Client{Timeout: 10 * time.Second}).Do(req)
	if err != nil {
		return nil
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode >= 400 {
		return nil
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil
	}
	return body
}

// toolForgeNotifications lists the authenticated user's pending forge
// notifications (mentions, reviews requested, issue assignments, etc).
func (b *MCPBridge) toolForgeNotifications(ctx context.Context, _ map[string]any) map[string]any {
	f, ok := b.forgeService()
	if !ok {
		return errResp("forge client not configured")
	}
	notes, err := f.Notifications.List(ctx)
	if err != nil {
		return map[string]any{"ok": false, "error": err.Error()}
	}
	out := make([]map[string]any, 0, len(notes))
	for _, n := range notes {
		entry := map[string]any{
			"id":         n.ID,
			"unread":     n.Unread,
			"pinned":     n.Pinned,
			"updated_at": n.UpdatedAt,
		}
		if n.Subject != nil {
			entry["title"] = n.Subject.Title
			entry["type"] = n.Subject.Type
			entry["url"] = n.Subject.HTMLURL
			entry["state"] = n.Subject.State
		}
		if n.Repository != nil {
			entry["repo"] = n.Repository.FullName
		}
		out = append(out, entry)
	}
	return map[string]any{"ok": true, "value": map[string]any{"notifications": out, "count": len(out)}}
}

type forgeRepo struct {
	Name, FullName, Description, HTMLURL string
	Private, Fork                         bool
	Stars                                 int64
	UpdatedAt                             string
}

func repoToInfo(r interface{}) forgeRepo {
	// types.Repository is bound at compile time; reflective coercion via
	// JSON keeps this file decoupled from the autogen types package.
	out := forgeRepo{}
	data := core.JSONMarshalString(r)
	parsed := map[string]any{}
	core.JSONUnmarshalString(data, &parsed)
	out.Name = stringOrEmpty(parsed["name"])
	out.FullName = stringOrEmpty(parsed["full_name"])
	out.Description = stringOrEmpty(parsed["description"])
	out.HTMLURL = stringOrEmpty(parsed["html_url"])
	out.Private = boolOrFalse(parsed["private"])
	out.Fork = boolOrFalse(parsed["fork"])
	if v, ok := parsed["stars_count"].(float64); ok {
		out.Stars = int64(v)
	}
	out.UpdatedAt = stringOrEmpty(parsed["updated_at"])
	return out
}

func stringOrEmpty(v any) string {
	if s, ok := v.(string); ok {
		return s
	}
	return ""
}

func boolOrFalse(v any) bool {
	if b, ok := v.(bool); ok {
		return b
	}
	return false
}

func userLogin(u any) string {
	if u == nil {
		return ""
	}
	data := core.JSONMarshalString(u)
	parsed := map[string]any{}
	core.JSONUnmarshalString(data, &parsed)
	return stringOrEmpty(parsed["login"])
}
