// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * buildBridge — typed wails wrapper over MCPBridge build_/process_
 * tools. /dev/build runs build_detect (cached) on entry and build_run
 * + process_* for live output streaming.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Detect probes the workspace for a buildable project. Result is
 * cached server-side (DuckDB, 5min TTL); pass force=true to bypass.
 */
export function Detect(input: $models.BuildDetectInput): $CancellablePromise<$models.BuildDetectOutput> {
    return $Call.ByID(3355951346, input).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ProcessKill stops a running process by its id.
 */
export function ProcessKill(input: $models.ProcessIDInput): $CancellablePromise<$models.ProcessKillOutput> {
    return $Call.ByID(168273006, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * ProcessList returns the current managed-process registry.
 */
export function ProcessList(): $CancellablePromise<$models.ProcessListOutput> {
    return $Call.ByID(2824346422).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ProcessOutput fetches accumulated stdout/stderr for a process.
 */
export function ProcessOutput(input: $models.ProcessIDInput): $CancellablePromise<$models.ProcessOutputResult> {
    return $Call.ByID(2340765867, input).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Run spawns the build command and returns the managed process_id so
 * the panel can poll output / kill.
 */
export function Run(input: $models.BuildRunInput): $CancellablePromise<$models.BuildRunOutput> {
    return $Call.ByID(971551146, input).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.BuildDetectOutput.createFrom;
const $$createType1 = $models.ProcessKillOutput.createFrom;
const $$createType2 = $models.ProcessListOutput.createFrom;
const $$createType3 = $models.ProcessOutputResult.createFrom;
const $$createType4 = $models.BuildRunOutput.createFrom;
