// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * cacheBridge — typed wails wrapper over MCPBridge cache_* tools
 * (DuckDB-backed app state at ~/.core/ide-cache.db).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Clear(input: $models.CacheClearInput): $CancellablePromise<$models.CacheClearOutput> {
    return $Call.ByID(3099216028, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Status(): $CancellablePromise<$models.CacheStatusOutput> {
    return $Call.ByID(3774407077).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.CacheClearOutput.createFrom;
const $$createType1 = $models.CacheStatusOutput.createFrom;
