// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.chatBridgeToolCall} input
 * @returns {$CancellablePromise<string>}
 */
export function CallTool(input) {
    return $Call.ByID(1464058329, input);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function ToolManifest() {
    return $Call.ByID(365903904);
}

/**
 * @returns {$CancellablePromise<any>}
 */
export function Tools() {
    return $Call.ByID(570139470);
}
