// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CallTool(input: $models.chatBridgeToolCall): $CancellablePromise<string> {
    return $Call.ByID(1464058329, input);
}

export function ToolManifest(): $CancellablePromise<string> {
    return $Call.ByID(365903904);
}

export function Tools(): $CancellablePromise<any> {
    return $Call.ByID(570139470);
}
