// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * containersBridge — typed wails wrapper over MCPBridge container_*
 * tools (runtime detection, list, logs).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Detect(input: $models.ContainerDetectInput): $CancellablePromise<$models.ContainerDetectOutput> {
    return $Call.ByID(1560153766, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function List(input: $models.ContainerListInput): $CancellablePromise<$models.ContainerListOutput> {
    return $Call.ByID(207415213, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Logs(input: $models.ContainerLogsInput): $CancellablePromise<$models.ContainerLogsOutput> {
    return $Call.ByID(2140232810, input).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ContainerDetectOutput.createFrom;
const $$createType1 = $models.ContainerListOutput.createFrom;
const $$createType2 = $models.ContainerLogsOutput.createFrom;
