// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * dataBridge — typed wails wrapper over MCPBridge orm_* tools (Memium /
 * DuckDB-backed ORM surface).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Backend(input: $models.DataBackendInput): $CancellablePromise<$models.DataBackendOutput> {
    return $Call.ByID(2293120631, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Count(input: $models.DataCountInput): $CancellablePromise<$models.DataCountOutput> {
    return $Call.ByID(3481263804, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Delete(input: $models.DataDeleteInput): $CancellablePromise<$models.DataMutationOutput> {
    return $Call.ByID(3164780306, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Get(input: $models.DataGetInput): $CancellablePromise<$models.DataRowsOutput> {
    return $Call.ByID(1361052031, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Save(input: $models.DataSaveInput): $CancellablePromise<$models.DataMutationOutput> {
    return $Call.ByID(1520664800, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Tables(): $CancellablePromise<$models.DataTablesOutput> {
    return $Call.ByID(2017873804).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DataBackendOutput.createFrom;
const $$createType1 = $models.DataCountOutput.createFrom;
const $$createType2 = $models.DataMutationOutput.createFrom;
const $$createType3 = $models.DataRowsOutput.createFrom;
const $$createType4 = $models.DataTablesOutput.createFrom;
