// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * devopsBridge — typed wails wrapper over MCPBridge devops_* tools
 * (secrets scan, gitleaks, playbooks).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Gitleaks(input: $models.DevopsScanInput): $CancellablePromise<$models.DevopsScanOutput> {
    return $Call.ByID(2989448570, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Playbooks(input: $models.DevopsScanInput): $CancellablePromise<$models.DevopsPlaybooksOutput> {
    return $Call.ByID(218474422, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SecretsScan(input: $models.DevopsScanInput): $CancellablePromise<$models.DevopsScanOutput> {
    return $Call.ByID(1378540594, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DevopsScanOutput.createFrom;
const $$createType1 = $models.DevopsPlaybooksOutput.createFrom;
