// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * fileBridge — typed wails wrapper over MCPBridge file_/dir_/lang_
 * tools. Hot path for the explorer panel via FileEditorStore (every
 * directory navigation, every Monaco tab open, every save).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Dir lists a directory's children. Returns OK=false + Error when the
 * path doesn't exist or isn't a directory; the explorer surfaces this
 * as a tree-row error pill.
 */
export function Dir(input: $models.DirListInput): $CancellablePromise<$models.DirListOutput> {
    return $Call.ByID(4004341742, input).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * LangDetect returns the language id for Monaco syntax highlighting.
 */
export function LangDetect(input: $models.LangDetectInput): $CancellablePromise<$models.LangDetectOutput> {
    return $Call.ByID(3322773192, input).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Read reads a file's full content. Used by Monaco when a tab opens.
 */
export function Read(input: $models.FileReadInput): $CancellablePromise<$models.FileReadOutput> {
    return $Call.ByID(2203256307, input).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Write persists Monaco's buffer back to disk. ⌘S calls this.
 */
export function Write(input: $models.FileWriteInput): $CancellablePromise<$models.FileWriteOutput> {
    return $Call.ByID(2832532242, input).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DirListOutput.createFrom;
const $$createType1 = $models.LangDetectOutput.createFrom;
const $$createType2 = $models.FileReadOutput.createFrom;
const $$createType3 = $models.FileWriteOutput.createFrom;
