// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * gitBridge — typed wails wrapper over MCPBridge git_* tools. /dev/git
 * is the source-control surface; these are called every time the user
 * stages, diffs, commits, switches branches.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Add(input: $models.GitAddInput): $CancellablePromise<$models.GitAddOutput> {
    return $Call.ByID(189924156, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Branch(input: $models.GitPathInput): $CancellablePromise<$models.GitBranchOutput> {
    return $Call.ByID(2147790781, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Commit(input: $models.GitCommitInput): $CancellablePromise<$models.GitCommitOutput> {
    return $Call.ByID(2541540052, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Diff(input: $models.GitDiffInput): $CancellablePromise<$models.GitDiffOutput> {
    return $Call.ByID(1089742978, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Status(input: $models.GitPathInput): $CancellablePromise<$models.GitStatusOutput> {
    return $Call.ByID(419743783, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Unstage(input: $models.GitUnstageInput): $CancellablePromise<$models.GitAddOutput> {
    return $Call.ByID(498850252, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.GitAddOutput.createFrom;
const $$createType1 = $models.GitBranchOutput.createFrom;
const $$createType2 = $models.GitCommitOutput.createFrom;
const $$createType3 = $models.GitDiffOutput.createFrom;
const $$createType4 = $models.GitStatusOutput.createFrom;
