// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * lemlabBridge — Wails wrapper for the LEM.Lab training studio plugin.
 * Mirrors the service contracts from LEM/cmd/lem-desktop/{dashboard,docker,
 * agent_runner}.go so the bridge body can be swapped to real go-mlx /
 * InfluxDB / docker backends without changing the FE wire shape.
 * 
 * v1: returns fixture data so the page renders end-to-end. The contract
 * is the load-bearing artifact, not the values.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AgentStatus returns the current scoring agent state.
 * v1: fixtures; future: read from AgentRunner.
 */
export function AgentStatus(): $CancellablePromise<$models.LemAgentStatus> {
    return $Call.ByID(2125016817).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetServices returns the docker compose stack status.
 * v1: fixtures; future: docker compose ps --format json against the
 * configured compose file.
 */
export function GetServices(): $CancellablePromise<$models.LemStackStatus> {
    return $Call.ByID(968831058).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSnapshot returns the complete dashboard state.
 * v1: fixture data; future: query InfluxDB + docker compose ps + agent
 * runner state in parallel and roll up.
 */
export function GetSnapshot(): $CancellablePromise<$models.LemSnapshot> {
    return $Call.ByID(427265346).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Refresh forces an immediate data refresh.
 * v1: no-op (fixtures don't refresh); future: trigger underlying poller.
 */
export function Refresh(): $CancellablePromise<$models.LemActionResult> {
    return $Call.ByID(2059072009).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * RunQuery executes an ad-hoc SQL query against the LEM DuckDB.
 * v1: returns empty result with placeholder error; future: open db at
 * snapshot.DBPath and run the query.
 */
export function RunQuery(sql: string): $CancellablePromise<$models.LemQueryResult> {
    return $Call.ByID(1965494145, sql).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * StartAgent begins the scoring agent in a background goroutine.
 * v1: no-op; future: spawn pkg/lem.RunAgent with configured args.
 */
export function StartAgent(): $CancellablePromise<$models.LemActionResult> {
    return $Call.ByID(2404619487).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * StartStack brings up the docker compose stack.
 * v1: no-op; future: docker compose up -d.
 */
export function StartStack(): $CancellablePromise<$models.LemActionResult> {
    return $Call.ByID(4209745146).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * StopAgent stops the scoring agent.
 * v1: no-op; future: cancel agent context.
 */
export function StopAgent(): $CancellablePromise<$models.LemActionResult> {
    return $Call.ByID(2685164095).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * StopStack tears down the docker compose stack.
 * v1: no-op; future: docker compose down.
 */
export function StopStack(): $CancellablePromise<$models.LemActionResult> {
    return $Call.ByID(236899162).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LemAgentStatus.createFrom;
const $$createType1 = $models.LemStackStatus.createFrom;
const $$createType2 = $models.LemSnapshot.createFrom;
const $$createType3 = $models.LemActionResult.createFrom;
const $$createType4 = $models.LemQueryResult.createFrom;
