// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * lintBridge — typed wails wrapper over MCPBridge lint_run / lint_catalog.
 * Reuses the existing LintRunOutput / LintIssue types from lint_bridge.go
 * since they already match the FE's wire shape exactly (rule_id, title,
 * severity, file, line, match, fix + severity counts).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Catalog returns the configured tool catalog (rules + plugins).
 */
export function Catalog(): $CancellablePromise<$models.WailsLintCatalogOutput> {
    return $Call.ByID(166445909).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Run executes core-lint against the workspace and returns the
 * canonical issues + severity counts. Reuses the existing
 * LintRunOutput type so the FE binding matches the legacy
 * callBridge wire shape.
 */
export function Run(input: $models.WailsLintRunInput): $CancellablePromise<$models.LintRunOutput> {
    return $Call.ByID(3673681175, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.WailsLintCatalogOutput.createFrom;
const $$createType1 = $models.LintRunOutput.createFrom;
