// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * localesBridge — typed wails wrapper over MCPBridge i18n_* tools
 * (translation coverage matrix over core/go-i18n).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Scan(): $CancellablePromise<$models.I18nScanOutput> {
    return $Call.ByID(4128889433).then(($result: any) => {
        return $$createType0($result);
    });
}

export function View(input: $models.I18nViewInput): $CancellablePromise<$models.I18nViewOutput> {
    return $Call.ByID(382819185, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.I18nScanOutput.createFrom;
const $$createType1 = $models.I18nViewOutput.createFrom;
