// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * marketplaceBridge — typed wails wrapper over MCPBridge pkg_* tools
 * (marketplace browse / install / remove via core/scm).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Install(input: $models.MarketplaceCodeInput): $CancellablePromise<$models.MarketplaceMutationOutput> {
    return $Call.ByID(3626306139, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Installed(): $CancellablePromise<$models.MarketplaceInstalledOutput> {
    return $Call.ByID(4203699418).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Remove(input: $models.MarketplaceCodeInput): $CancellablePromise<$models.MarketplaceMutationOutput> {
    return $Call.ByID(2017393520, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Search(input: $models.MarketplaceSearchInput): $CancellablePromise<$models.MarketplaceSearchOutput> {
    return $Call.ByID(962323444, input).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MarketplaceMutationOutput.createFrom;
const $$createType1 = $models.MarketplaceInstalledOutput.createFrom;
const $$createType2 = $models.MarketplaceSearchOutput.createFrom;
