// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * memoryBridge — typed wails wrapper over MCPBridge memory_list /
 * memory_search. /dev/memory inspects Cladius's persistent memory.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function List(input: $models.MemoryListInput): $CancellablePromise<$models.MemoryListOutput> {
    return $Call.ByID(330359896, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Search(input: $models.MemorySearchInput): $CancellablePromise<$models.MemorySearchOutput> {
    return $Call.ByID(805200204, input).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.MemoryListOutput.createFrom;
const $$createType1 = $models.MemorySearchOutput.createFrom;
