// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class chatBridgeToolCall {
    /**
     * Creates a new chatBridgeToolCall instance.
     * @param {Partial<chatBridgeToolCall>} [$$source = {}] - The source object to create the chatBridgeToolCall.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["arguments"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new chatBridgeToolCall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {chatBridgeToolCall}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField1_0($$parsedSource["arguments"]);
        }
        return new chatBridgeToolCall(/** @type {Partial<chatBridgeToolCall>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
