// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ActiveSession {
    "id": string;
    "path": string;
    "project"?: string;
    "project_path"?: string;
    "size_bytes"?: number;
    "modified"?: string;
    "age_seconds"?: number;

    /** Creates a new ActiveSession instance. */
    constructor($$source: Partial<ActiveSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveSession instance from a string or object.
     */
    static createFrom($$source: any = {}): ActiveSession {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActiveSession($$parsedSource as Partial<ActiveSession>);
    }
}

export class BuildDetectInput {
    "path": string;
    "force"?: boolean;

    /** Creates a new BuildDetectInput instance. */
    constructor($$source: Partial<BuildDetectInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildDetectInput instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildDetectInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildDetectInput($$parsedSource as Partial<BuildDetectInput>);
    }
}

export class BuildDetectOutput {
    "ok": boolean;
    "path"?: string;
    "tool"?: string;
    "source"?: string;
    "command"?: string;
    "args"?: string[];
    "frameworks"?: string[];
    "cache_hit"?: boolean;
    "cache_age_s"?: number;
    "error"?: string;

    /** Creates a new BuildDetectOutput instance. */
    constructor($$source: Partial<BuildDetectOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildDetectOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildDetectOutput {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField5_0($$parsedSource["args"]);
        }
        if ("frameworks" in $$parsedSource) {
            $$parsedSource["frameworks"] = $$createField6_0($$parsedSource["frameworks"]);
        }
        return new BuildDetectOutput($$parsedSource as Partial<BuildDetectOutput>);
    }
}

export class BuildRunInput {
    "path": string;
    "command"?: string;
    "args"?: string[];

    /** Creates a new BuildRunInput instance. */
    constructor($$source: Partial<BuildRunInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildRunInput instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildRunInput {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField2_0($$parsedSource["args"]);
        }
        return new BuildRunInput($$parsedSource as Partial<BuildRunInput>);
    }
}

export class BuildRunOutput {
    "ok": boolean;
    "process_id"?: string;
    "error"?: string;

    /** Creates a new BuildRunOutput instance. */
    constructor($$source: Partial<BuildRunOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BuildRunOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): BuildRunOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BuildRunOutput($$parsedSource as Partial<BuildRunOutput>);
    }
}

/**
 * ChatConversationDetail is the LoadConversation result — the
 * conversation metadata plus its full message list.
 */
export class ChatConversationDetail {
    "id": string;
    "title": string;
    "model": string;
    "created_at": string;
    "updated_at": string;
    "messages": ChatMessageOutput[];

    /** Creates a new ChatConversationDetail instance. */
    constructor($$source: Partial<ChatConversationDetail> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("messages" in $$source)) {
            this["messages"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatConversationDetail instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatConversationDetail {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("messages" in $$parsedSource) {
            $$parsedSource["messages"] = $$createField5_0($$parsedSource["messages"]);
        }
        return new ChatConversationDetail($$parsedSource as Partial<ChatConversationDetail>);
    }
}

export class ChatConversationLoadOutput {
    "conversation": ChatConversationDetail;

    /** Creates a new ChatConversationLoadOutput instance. */
    constructor($$source: Partial<ChatConversationLoadOutput> = {}) {
        if (!("conversation" in $$source)) {
            this["conversation"] = (new ChatConversationDetail());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatConversationLoadOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatConversationLoadOutput {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conversation" in $$parsedSource) {
            $$parsedSource["conversation"] = $$createField0_0($$parsedSource["conversation"]);
        }
        return new ChatConversationLoadOutput($$parsedSource as Partial<ChatConversationLoadOutput>);
    }
}

/**
 * ChatConversationOutput mirrors gui chat Conversation (without the
 * nested Messages — those load via History or LoadConversation).
 */
export class ChatConversationOutput {
    "id": string;
    "title": string;
    "model": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new ChatConversationOutput instance. */
    constructor($$source: Partial<ChatConversationOutput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatConversationOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatConversationOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatConversationOutput($$parsedSource as Partial<ChatConversationOutput>);
    }
}

export class ChatConversationsListOutput {
    "conversations": ChatConversationOutput[];

    /** Creates a new ChatConversationsListOutput instance. */
    constructor($$source: Partial<ChatConversationsListOutput> = {}) {
        if (!("conversations" in $$source)) {
            this["conversations"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatConversationsListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatConversationsListOutput {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("conversations" in $$parsedSource) {
            $$parsedSource["conversations"] = $$createField0_0($$parsedSource["conversations"]);
        }
        return new ChatConversationsListOutput($$parsedSource as Partial<ChatConversationsListOutput>);
    }
}

/**
 * ChatMessageOutput mirrors the gui chat Message shape.
 */
export class ChatMessageOutput {
    "id": string;
    "role": string;
    "content": string;
    "created_at": string;
    "model"?: string;

    /** Creates a new ChatMessageOutput instance. */
    constructor($$source: Partial<ChatMessageOutput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatMessageOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatMessageOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatMessageOutput($$parsedSource as Partial<ChatMessageOutput>);
    }
}

/**
 * ChatModelOutput mirrors the gui chat package's ModelEntry shape
 * JSON-tagged so the wails generator emits a binding the existing
 * /dev/chat panel can bind without renames.
 */
export class ChatModelOutput {
    "name": string;
    "size"?: number;
    "status"?: string;
    "architecture"?: string;
    "quant_bits"?: number;
    "size_bytes"?: number;
    "loaded"?: boolean;
    "backend"?: string;

    /** Creates a new ChatModelOutput instance. */
    constructor($$source: Partial<ChatModelOutput> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatModelOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatModelOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatModelOutput($$parsedSource as Partial<ChatModelOutput>);
    }
}

export class ChatModelsOutput {
    "models": ChatModelOutput[];

    /** Creates a new ChatModelsOutput instance. */
    constructor($$source: Partial<ChatModelsOutput> = {}) {
        if (!("models" in $$source)) {
            this["models"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatModelsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatModelsOutput {
        const $$createField0_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("models" in $$parsedSource) {
            $$parsedSource["models"] = $$createField0_0($$parsedSource["models"]);
        }
        return new ChatModelsOutput($$parsedSource as Partial<ChatModelsOutput>);
    }
}

export class ChatSelectModelInput {
    "conversation_id"?: string;
    "model": string;

    /** Creates a new ChatSelectModelInput instance. */
    constructor($$source: Partial<ChatSelectModelInput> = {}) {
        if (!("model" in $$source)) {
            this["model"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSelectModelInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatSelectModelInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSelectModelInput($$parsedSource as Partial<ChatSelectModelInput>);
    }
}

export class ChatSelectModelOutput {
    "ok": boolean;

    /** Creates a new ChatSelectModelOutput instance. */
    constructor($$source: Partial<ChatSelectModelOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSelectModelOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatSelectModelOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSelectModelOutput($$parsedSource as Partial<ChatSelectModelOutput>);
    }
}

/**
 * ChatSendInput is the panel's Send button payload.
 */
export class ChatSendInput {
    "conversation_id"?: string;
    "content": string;
    "model"?: string;

    /** Creates a new ChatSendInput instance. */
    constructor($$source: Partial<ChatSendInput> = {}) {
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSendInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatSendInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSendInput($$parsedSource as Partial<ChatSendInput>);
    }
}

export class ChatSendOutput {
    "message_id": string;

    /** Creates a new ChatSendOutput instance. */
    constructor($$source: Partial<ChatSendOutput> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChatSendOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ChatSendOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChatSendOutput($$parsedSource as Partial<ChatSendOutput>);
    }
}

export class DevopsPlaybookEntry {
    "name": string;
    "path"?: string;
    "description"?: string;
    "tags"?: string[];

    /** Creates a new DevopsPlaybookEntry instance. */
    constructor($$source: Partial<DevopsPlaybookEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevopsPlaybookEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DevopsPlaybookEntry {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField3_0($$parsedSource["tags"]);
        }
        return new DevopsPlaybookEntry($$parsedSource as Partial<DevopsPlaybookEntry>);
    }
}

export class DevopsPlaybooksOutput {
    "ok": boolean;
    "playbooks"?: DevopsPlaybookEntry[];
    "cache_hit"?: boolean;
    "cache_age_s"?: number;
    "error"?: string;

    /** Creates a new DevopsPlaybooksOutput instance. */
    constructor($$source: Partial<DevopsPlaybooksOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevopsPlaybooksOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DevopsPlaybooksOutput {
        const $$createField1_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("playbooks" in $$parsedSource) {
            $$parsedSource["playbooks"] = $$createField1_0($$parsedSource["playbooks"]);
        }
        return new DevopsPlaybooksOutput($$parsedSource as Partial<DevopsPlaybooksOutput>);
    }
}

export class DevopsScanFinding {
    "file"?: string;
    "line"?: number;
    "rule"?: string;
    "severity"?: string;
    "match"?: string;

    /** Creates a new DevopsScanFinding instance. */
    constructor($$source: Partial<DevopsScanFinding> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevopsScanFinding instance from a string or object.
     */
    static createFrom($$source: any = {}): DevopsScanFinding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevopsScanFinding($$parsedSource as Partial<DevopsScanFinding>);
    }
}

export class DevopsScanInput {
    "path"?: string;
    "force"?: boolean;

    /** Creates a new DevopsScanInput instance. */
    constructor($$source: Partial<DevopsScanInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevopsScanInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DevopsScanInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DevopsScanInput($$parsedSource as Partial<DevopsScanInput>);
    }
}

export class DevopsScanOutput {
    "ok": boolean;
    "findings"?: DevopsScanFinding[];
    "cache_hit"?: boolean;
    "cache_age_s"?: number;
    "error"?: string;

    /** Creates a new DevopsScanOutput instance. */
    constructor($$source: Partial<DevopsScanOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DevopsScanOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DevopsScanOutput {
        const $$createField1_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("findings" in $$parsedSource) {
            $$parsedSource["findings"] = $$createField1_0($$parsedSource["findings"]);
        }
        return new DevopsScanOutput($$parsedSource as Partial<DevopsScanOutput>);
    }
}

export class DirEntry {
    "name": string;
    "is_dir": boolean;
    "size_bytes"?: number;
    "modified"?: string;

    /** Creates a new DirEntry instance. */
    constructor($$source: Partial<DirEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("is_dir" in $$source)) {
            this["is_dir"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirEntry($$parsedSource as Partial<DirEntry>);
    }
}

export class DirListInput {
    "path": string;

    /** Creates a new DirListInput instance. */
    constructor($$source: Partial<DirListInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): DirListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DirListInput($$parsedSource as Partial<DirListInput>);
    }
}

export class DirListOutput {
    "ok": boolean;
    "path"?: string;
    "entries"?: DirEntry[];
    "error"?: string;

    /** Creates a new DirListOutput instance. */
    constructor($$source: Partial<DirListOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DirListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): DirListOutput {
        const $$createField2_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField2_0($$parsedSource["entries"]);
        }
        return new DirListOutput($$parsedSource as Partial<DirListOutput>);
    }
}

export class FileReadInput {
    "path": string;

    /** Creates a new FileReadInput instance. */
    constructor($$source: Partial<FileReadInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileReadInput instance from a string or object.
     */
    static createFrom($$source: any = {}): FileReadInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileReadInput($$parsedSource as Partial<FileReadInput>);
    }
}

export class FileReadOutput {
    "ok": boolean;
    "path"?: string;
    "content"?: string;
    "error"?: string;

    /** Creates a new FileReadOutput instance. */
    constructor($$source: Partial<FileReadOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileReadOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): FileReadOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileReadOutput($$parsedSource as Partial<FileReadOutput>);
    }
}

export class FileWriteInput {
    "path": string;
    "content": string;

    /** Creates a new FileWriteInput instance. */
    constructor($$source: Partial<FileWriteInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileWriteInput instance from a string or object.
     */
    static createFrom($$source: any = {}): FileWriteInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileWriteInput($$parsedSource as Partial<FileWriteInput>);
    }
}

export class FileWriteOutput {
    "ok": boolean;
    "error"?: string;

    /** Creates a new FileWriteOutput instance. */
    constructor($$source: Partial<FileWriteOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileWriteOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): FileWriteOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileWriteOutput($$parsedSource as Partial<FileWriteOutput>);
    }
}

export class GitAddInput {
    "path": string;
    "files"?: string[];
    "all"?: boolean;

    /** Creates a new GitAddInput instance. */
    constructor($$source: Partial<GitAddInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitAddInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitAddInput {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new GitAddInput($$parsedSource as Partial<GitAddInput>);
    }
}

export class GitAddOutput {
    "ok": boolean;
    "error"?: string;

    /** Creates a new GitAddOutput instance. */
    constructor($$source: Partial<GitAddOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitAddOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitAddOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitAddOutput($$parsedSource as Partial<GitAddOutput>);
    }
}

export class GitBranchOutput {
    "ok": boolean;
    "branch"?: string;
    "ahead"?: number;
    "behind"?: number;
    "error"?: string;

    /** Creates a new GitBranchOutput instance. */
    constructor($$source: Partial<GitBranchOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitBranchOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitBranchOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitBranchOutput($$parsedSource as Partial<GitBranchOutput>);
    }
}

export class GitCommitInput {
    "path": string;
    "message": string;

    /** Creates a new GitCommitInput instance. */
    constructor($$source: Partial<GitCommitInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitCommitInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitCommitInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitCommitInput($$parsedSource as Partial<GitCommitInput>);
    }
}

export class GitCommitOutput {
    "ok": boolean;
    "sha"?: string;
    "error"?: string;

    /** Creates a new GitCommitOutput instance. */
    constructor($$source: Partial<GitCommitOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitCommitOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitCommitOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitCommitOutput($$parsedSource as Partial<GitCommitOutput>);
    }
}

export class GitDiffInput {
    "path": string;
    "file": string;
    "staged"?: boolean;

    /** Creates a new GitDiffInput instance. */
    constructor($$source: Partial<GitDiffInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitDiffInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitDiffInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitDiffInput($$parsedSource as Partial<GitDiffInput>);
    }
}

export class GitDiffOutput {
    "ok": boolean;
    "diff"?: string;
    "error"?: string;

    /** Creates a new GitDiffOutput instance. */
    constructor($$source: Partial<GitDiffOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitDiffOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitDiffOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitDiffOutput($$parsedSource as Partial<GitDiffOutput>);
    }
}

export class GitEntry {
    "path": string;
    "index_status"?: string;
    "worktree_status"?: string;
    "staged"?: boolean;
    "unstaged"?: boolean;
    "untracked"?: boolean;

    /** Creates a new GitEntry instance. */
    constructor($$source: Partial<GitEntry> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): GitEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitEntry($$parsedSource as Partial<GitEntry>);
    }
}

export class GitPathInput {
    "path": string;

    /** Creates a new GitPathInput instance. */
    constructor($$source: Partial<GitPathInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitPathInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitPathInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GitPathInput($$parsedSource as Partial<GitPathInput>);
    }
}

export class GitStatusOutput {
    "ok": boolean;
    "entries"?: GitEntry[];
    "error"?: string;

    /** Creates a new GitStatusOutput instance. */
    constructor($$source: Partial<GitStatusOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitStatusOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitStatusOutput {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new GitStatusOutput($$parsedSource as Partial<GitStatusOutput>);
    }
}

export class GitUnstageInput {
    "path": string;
    "files": string[];

    /** Creates a new GitUnstageInput instance. */
    constructor($$source: Partial<GitUnstageInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitUnstageInput instance from a string or object.
     */
    static createFrom($$source: any = {}): GitUnstageInput {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new GitUnstageInput($$parsedSource as Partial<GitUnstageInput>);
    }
}

export class LangDetectInput {
    "path": string;

    /** Creates a new LangDetectInput instance. */
    constructor($$source: Partial<LangDetectInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LangDetectInput instance from a string or object.
     */
    static createFrom($$source: any = {}): LangDetectInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LangDetectInput($$parsedSource as Partial<LangDetectInput>);
    }
}

export class LangDetectOutput {
    "ok": boolean;
    "lang"?: string;
    "error"?: string;

    /** Creates a new LangDetectOutput instance. */
    constructor($$source: Partial<LangDetectOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LangDetectOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LangDetectOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LangDetectOutput($$parsedSource as Partial<LangDetectOutput>);
    }
}

/**
 * LintIssue mirrors a single result row from `core-lint lint check --format json`.
 */
export class LintIssue {
    "rule_id": string;
    "title": string;
    "severity": string;
    "file": string;
    "line": number;
    "match": string;
    "fix": string;

    /** Creates a new LintIssue instance. */
    constructor($$source: Partial<LintIssue> = {}) {
        if (!("rule_id" in $$source)) {
            this["rule_id"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = "";
        }
        if (!("file" in $$source)) {
            this["file"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("match" in $$source)) {
            this["match"] = "";
        }
        if (!("fix" in $$source)) {
            this["fix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LintIssue instance from a string or object.
     */
    static createFrom($$source: any = {}): LintIssue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LintIssue($$parsedSource as Partial<LintIssue>);
    }
}

/**
 * LintRunOutput is the wrapped response shape — adds severity counts
 * and the absolute-path resolution used by the frontend's click-to-open.
 */
export class LintRunOutput {
    "path": string;
    "issues": LintIssue[];
    "counts": { [_ in string]?: number };
    "total": number;
    "binary_path": string;
    "duration_ms": number;

    /** Creates a new LintRunOutput instance. */
    constructor($$source: Partial<LintRunOutput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }
        if (!("counts" in $$source)) {
            this["counts"] = {};
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("binary_path" in $$source)) {
            this["binary_path"] = "";
        }
        if (!("duration_ms" in $$source)) {
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LintRunOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): LintRunOutput {
        const $$createField1_0 = $$createType17;
        const $$createField2_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField1_0($$parsedSource["issues"]);
        }
        if ("counts" in $$parsedSource) {
            $$parsedSource["counts"] = $$createField2_0($$parsedSource["counts"]);
        }
        return new LintRunOutput($$parsedSource as Partial<LintRunOutput>);
    }
}

export class MemoryEntry {
    "name": string;
    "type"?: string;
    "description"?: string;
    "path"?: string;
    "size_bytes"?: number;
    "modified"?: string;

    /** Creates a new MemoryEntry instance. */
    constructor($$source: Partial<MemoryEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryEntry($$parsedSource as Partial<MemoryEntry>);
    }
}

export class MemoryListInput {
    "sort"?: string;
    "force"?: boolean;

    /** Creates a new MemoryListInput instance. */
    constructor($$source: Partial<MemoryListInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemoryListInput($$parsedSource as Partial<MemoryListInput>);
    }
}

export class MemoryListOutput {
    "ok": boolean;
    "entries"?: MemoryEntry[];
    "cache_hit"?: boolean;
    "cache_age_s"?: number;
    "error"?: string;

    /** Creates a new MemoryListOutput instance. */
    constructor($$source: Partial<MemoryListOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemoryListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MemoryListOutput {
        const $$createField1_0 = $$createType20;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField1_0($$parsedSource["entries"]);
        }
        return new MemoryListOutput($$parsedSource as Partial<MemoryListOutput>);
    }
}

export class MemorySearchHit {
    "name": string;
    "path"?: string;
    "snippet"?: string;
    "score"?: number;

    /** Creates a new MemorySearchHit instance. */
    constructor($$source: Partial<MemorySearchHit> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemorySearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): MemorySearchHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemorySearchHit($$parsedSource as Partial<MemorySearchHit>);
    }
}

export class MemorySearchInput {
    "query": string;

    /** Creates a new MemorySearchInput instance. */
    constructor($$source: Partial<MemorySearchInput> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemorySearchInput instance from a string or object.
     */
    static createFrom($$source: any = {}): MemorySearchInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MemorySearchInput($$parsedSource as Partial<MemorySearchInput>);
    }
}

export class MemorySearchOutput {
    "ok": boolean;
    "hits"?: MemorySearchHit[];
    "error"?: string;

    /** Creates a new MemorySearchOutput instance. */
    constructor($$source: Partial<MemorySearchOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MemorySearchOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): MemorySearchOutput {
        const $$createField1_0 = $$createType22;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField1_0($$parsedSource["hits"]);
        }
        return new MemorySearchOutput($$parsedSource as Partial<MemorySearchOutput>);
    }
}

export class P2PPeer {
    "id": string;
    "topic": string;
    "connected": boolean;
    "seen_at": string;

    /** Creates a new P2PPeer instance. */
    constructor($$source: Partial<P2PPeer> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("seen_at" in $$source)) {
            this["seen_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new P2PPeer instance from a string or object.
     */
    static createFrom($$source: any = {}): P2PPeer {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new P2PPeer($$parsedSource as Partial<P2PPeer>);
    }
}

/**
 * P2PPublishInput matches the existing tools_p2p.go P2PPublishInput
 * so the FE doesn't need to rename anything.
 */
export class P2PPublishInput {
    "topic": string;
    "route"?: string;
    "sender_id"?: string;
    "payload"?: { [_ in string]?: any };

    /** Creates a new P2PPublishInput instance. */
    constructor($$source: Partial<P2PPublishInput> = {}) {
        if (!("topic" in $$source)) {
            this["topic"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new P2PPublishInput instance from a string or object.
     */
    static createFrom($$source: any = {}): P2PPublishInput {
        const $$createField3_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("payload" in $$parsedSource) {
            $$parsedSource["payload"] = $$createField3_0($$parsedSource["payload"]);
        }
        return new P2PPublishInput($$parsedSource as Partial<P2PPublishInput>);
    }
}

export class P2PPublishOutput {
    "success": boolean;

    /** Creates a new P2PPublishOutput instance. */
    constructor($$source: Partial<P2PPublishOutput> = {}) {
        if (!("success" in $$source)) {
            this["success"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new P2PPublishOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): P2PPublishOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new P2PPublishOutput($$parsedSource as Partial<P2PPublishOutput>);
    }
}

/**
 * P2PStateOutput mirrors the gui p2p.State payload that the
 * /dev/p2p panel binds. Field names are JSON-tagged to match the
 * existing callBridge contract so the swap is transparent.
 */
export class P2PStateOutput {
    "node_id"?: string;
    "listen_addr"?: string;
    "peers"?: P2PPeer[];

    /** Creates a new P2PStateOutput instance. */
    constructor($$source: Partial<P2PStateOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new P2PStateOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): P2PStateOutput {
        const $$createField2_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("peers" in $$parsedSource) {
            $$parsedSource["peers"] = $$createField2_0($$parsedSource["peers"]);
        }
        return new P2PStateOutput($$parsedSource as Partial<P2PStateOutput>);
    }
}

export class ProcessIDInput {
    "id": string;

    /** Creates a new ProcessIDInput instance. */
    constructor($$source: Partial<ProcessIDInput> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessIDInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessIDInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessIDInput($$parsedSource as Partial<ProcessIDInput>);
    }
}

export class ProcessKillOutput {
    "ok": boolean;
    "error"?: string;

    /** Creates a new ProcessKillOutput instance. */
    constructor($$source: Partial<ProcessKillOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessKillOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessKillOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessKillOutput($$parsedSource as Partial<ProcessKillOutput>);
    }
}

export class ProcessListEntry {
    "id": string;
    "status"?: string;

    /** Creates a new ProcessListEntry instance. */
    constructor($$source: Partial<ProcessListEntry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessListEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessListEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessListEntry($$parsedSource as Partial<ProcessListEntry>);
    }
}

export class ProcessListOutput {
    "ok": boolean;
    "processes"?: ProcessListEntry[];
    "error"?: string;

    /** Creates a new ProcessListOutput instance. */
    constructor($$source: Partial<ProcessListOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessListOutput {
        const $$createField1_0 = $$createType27;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("processes" in $$parsedSource) {
            $$parsedSource["processes"] = $$createField1_0($$parsedSource["processes"]);
        }
        return new ProcessListOutput($$parsedSource as Partial<ProcessListOutput>);
    }
}

export class ProcessOutputResult {
    "ok": boolean;
    "output"?: string;
    "error"?: string;

    /** Creates a new ProcessOutputResult instance. */
    constructor($$source: Partial<ProcessOutputResult> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessOutputResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ProcessOutputResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessOutputResult($$parsedSource as Partial<ProcessOutputResult>);
    }
}

export class RepoEntry {
    "name": string;
    "path": string;
    "branch"?: string;
    "modified"?: number;
    "untracked"?: number;
    "staged"?: number;
    "ahead"?: number;
    "behind"?: number;
    "dirty"?: boolean;
    "error"?: string;

    /** Creates a new RepoEntry instance. */
    constructor($$source: Partial<RepoEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RepoEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RepoEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RepoEntry($$parsedSource as Partial<RepoEntry>);
    }
}

export class ReposStatusInput {
    "roots"?: string[];
    "force"?: boolean;

    /** Creates a new ReposStatusInput instance. */
    constructor($$source: Partial<ReposStatusInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReposStatusInput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReposStatusInput {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("roots" in $$parsedSource) {
            $$parsedSource["roots"] = $$createField0_0($$parsedSource["roots"]);
        }
        return new ReposStatusInput($$parsedSource as Partial<ReposStatusInput>);
    }
}

export class ReposStatusOutput {
    "ok": boolean;
    "repos"?: RepoEntry[];
    "scanned"?: number;
    "cache_hit"?: boolean;
    "cache_age_s"?: number;
    "error"?: string;

    /** Creates a new ReposStatusOutput instance. */
    constructor($$source: Partial<ReposStatusOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReposStatusOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): ReposStatusOutput {
        const $$createField1_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("repos" in $$parsedSource) {
            $$parsedSource["repos"] = $$createField1_0($$parsedSource["repos"]);
        }
        return new ReposStatusOutput($$parsedSource as Partial<ReposStatusOutput>);
    }
}

export class SearchInput {
    "query": string;
    "path": string;
    "max_results"?: number;

    /** Creates a new SearchInput instance. */
    constructor($$source: Partial<SearchInput> = {}) {
        if (!("query" in $$source)) {
            this["query"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchInput($$parsedSource as Partial<SearchInput>);
    }
}

export class SearchMatch {
    "path": string;
    "line": number;
    "text": string;

    /** Creates a new SearchMatch instance. */
    constructor($$source: Partial<SearchMatch> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SearchMatch($$parsedSource as Partial<SearchMatch>);
    }
}

export class SearchOutput {
    "ok": boolean;
    "matches"?: SearchMatch[];
    "truncated"?: boolean;
    "error"?: string;

    /** Creates a new SearchOutput instance. */
    constructor($$source: Partial<SearchOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SearchOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SearchOutput {
        const $$createField1_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matches" in $$parsedSource) {
            $$parsedSource["matches"] = $$createField1_0($$parsedSource["matches"]);
        }
        return new SearchOutput($$parsedSource as Partial<SearchOutput>);
    }
}

export class SessionActiveInput {
    "since_minutes": number;

    /** Creates a new SessionActiveInput instance. */
    constructor($$source: Partial<SessionActiveInput> = {}) {
        if (!("since_minutes" in $$source)) {
            this["since_minutes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionActiveInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionActiveInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionActiveInput($$parsedSource as Partial<SessionActiveInput>);
    }
}

export class SessionActiveOutput {
    "ok": boolean;
    "active"?: ActiveSession[];
    "error"?: string;

    /** Creates a new SessionActiveOutput instance. */
    constructor($$source: Partial<SessionActiveOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionActiveOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionActiveOutput {
        const $$createField1_0 = $$createType33;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("active" in $$parsedSource) {
            $$parsedSource["active"] = $$createField1_0($$parsedSource["active"]);
        }
        return new SessionActiveOutput($$parsedSource as Partial<SessionActiveOutput>);
    }
}

export class SessionInspectInput {
    "path": string;
    "limit"?: number;

    /** Creates a new SessionInspectInput instance. */
    constructor($$source: Partial<SessionInspectInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionInspectInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionInspectInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionInspectInput($$parsedSource as Partial<SessionInspectInput>);
    }
}

export class SessionListInput {
    "project_dir": string;

    /** Creates a new SessionListInput instance. */
    constructor($$source: Partial<SessionListInput> = {}) {
        if (!("project_dir" in $$source)) {
            this["project_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionListInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionListInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionListInput($$parsedSource as Partial<SessionListInput>);
    }
}

export class SessionListOutput {
    "ok": boolean;
    "sessions"?: SessionSummary[];
    "error"?: string;

    /** Creates a new SessionListOutput instance. */
    constructor($$source: Partial<SessionListOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionListOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionListOutput {
        const $$createField1_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sessions" in $$parsedSource) {
            $$parsedSource["sessions"] = $$createField1_0($$parsedSource["sessions"]);
        }
        return new SessionListOutput($$parsedSource as Partial<SessionListOutput>);
    }
}

export class SessionProject {
    "name": string;
    "display_path": string;
    "path": string;
    "session_count": number;
    "latest_at"?: string;

    /** Creates a new SessionProject instance. */
    constructor($$source: Partial<SessionProject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("display_path" in $$source)) {
            this["display_path"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("session_count" in $$source)) {
            this["session_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionProject instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionProject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionProject($$parsedSource as Partial<SessionProject>);
    }
}

export class SessionProjectsInput {
    "force"?: boolean;

    /** Creates a new SessionProjectsInput instance. */
    constructor($$source: Partial<SessionProjectsInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionProjectsInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionProjectsInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionProjectsInput($$parsedSource as Partial<SessionProjectsInput>);
    }
}

export class SessionProjectsOutput {
    "ok": boolean;
    "projects"?: SessionProject[];
    "cache_hit"?: boolean;
    "cache_age_s"?: number;
    "error"?: string;

    /** Creates a new SessionProjectsOutput instance. */
    constructor($$source: Partial<SessionProjectsOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionProjectsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionProjectsOutput {
        const $$createField1_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("projects" in $$parsedSource) {
            $$parsedSource["projects"] = $$createField1_0($$parsedSource["projects"]);
        }
        return new SessionProjectsOutput($$parsedSource as Partial<SessionProjectsOutput>);
    }
}

export class SessionSearchHit {
    "session_id": string;
    "timestamp"?: string;
    "tool"?: string;
    "match"?: string;

    /** Creates a new SessionSearchHit instance. */
    constructor($$source: Partial<SessionSearchHit> = {}) {
        if (!("session_id" in $$source)) {
            this["session_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSearchHit instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSearchHit {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionSearchHit($$parsedSource as Partial<SessionSearchHit>);
    }
}

export class SessionSearchInput {
    "project_dir": string;
    "query": string;

    /** Creates a new SessionSearchInput instance. */
    constructor($$source: Partial<SessionSearchInput> = {}) {
        if (!("project_dir" in $$source)) {
            this["project_dir"] = "";
        }
        if (!("query" in $$source)) {
            this["query"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSearchInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSearchInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionSearchInput($$parsedSource as Partial<SessionSearchInput>);
    }
}

export class SessionSearchOutput {
    "ok": boolean;
    "hits"?: SessionSearchHit[];
    "error"?: string;

    /** Creates a new SessionSearchOutput instance. */
    constructor($$source: Partial<SessionSearchOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSearchOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSearchOutput {
        const $$createField1_0 = $$createType39;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hits" in $$parsedSource) {
            $$parsedSource["hits"] = $$createField1_0($$parsedSource["hits"]);
        }
        return new SessionSearchOutput($$parsedSource as Partial<SessionSearchOutput>);
    }
}

export class SessionSummary {
    "id": string;
    "path": string;
    "start_time"?: string;
    "end_time"?: string;
    "event_count"?: number;
    "size_bytes"?: number;

    /** Creates a new SessionSummary instance. */
    constructor($$source: Partial<SessionSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionSummary($$parsedSource as Partial<SessionSummary>);
    }
}

export class SessionTailInput {
    "path": string;
    "since_offset": number;
    "limit"?: number;

    /** Creates a new SessionTailInput instance. */
    constructor($$source: Partial<SessionTailInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("since_offset" in $$source)) {
            this["since_offset"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionTailInput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionTailInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionTailInput($$parsedSource as Partial<SessionTailInput>);
    }
}

export class SessionTailLiveEvent {
    "timestamp": string;
    "type"?: string;
    "role"?: string;
    "tool"?: string;
    "input"?: string;

    /** Creates a new SessionTailLiveEvent instance. */
    constructor($$source: Partial<SessionTailLiveEvent> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionTailLiveEvent instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionTailLiveEvent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionTailLiveEvent($$parsedSource as Partial<SessionTailLiveEvent>);
    }
}

export class SessionTailOutput {
    "ok": boolean;
    "events"?: SessionTailLiveEvent[];
    "next_offset"?: number;
    "error"?: string;

    /** Creates a new SessionTailOutput instance. */
    constructor($$source: Partial<SessionTailOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionTailOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): SessionTailOutput {
        const $$createField1_0 = $$createType41;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("events" in $$parsedSource) {
            $$parsedSource["events"] = $$createField1_0($$parsedSource["events"]);
        }
        return new SessionTailOutput($$parsedSource as Partial<SessionTailOutput>);
    }
}

export class StreamChannel {
    "name": string;
    "subscriber_count"?: number;
    "recent_frames"?: number;

    /** Creates a new StreamChannel instance. */
    constructor($$source: Partial<StreamChannel> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamChannel instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamChannel {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamChannel($$parsedSource as Partial<StreamChannel>);
    }
}

export class StreamChannelsOutput {
    "ok": boolean;
    "channels"?: StreamChannel[];
    "count"?: number;
    "broadcast_buf"?: number;
    "error"?: string;

    /** Creates a new StreamChannelsOutput instance. */
    constructor($$source: Partial<StreamChannelsOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamChannelsOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamChannelsOutput {
        const $$createField1_0 = $$createType43;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField1_0($$parsedSource["channels"]);
        }
        return new StreamChannelsOutput($$parsedSource as Partial<StreamChannelsOutput>);
    }
}

export class StreamConfig {
    "heartbeat_ms"?: number;
    "pong_timeout_ms"?: number;
    "write_timeout_ms"?: number;

    /** Creates a new StreamConfig instance. */
    constructor($$source: Partial<StreamConfig> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamConfig($$parsedSource as Partial<StreamConfig>);
    }
}

export class StreamFrame {
    "channel"?: string;
    "timestamp": string;
    "frame_text"?: string;
    "frame_bytes"?: number;

    /** Creates a new StreamFrame instance. */
    constructor($$source: Partial<StreamFrame> = {}) {
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamFrame instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamFrame {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamFrame($$parsedSource as Partial<StreamFrame>);
    }
}

export class StreamPublishInput {
    "mode"?: string;
    "channel"?: string;
    "frame"?: string;

    /** Creates a new StreamPublishInput instance. */
    constructor($$source: Partial<StreamPublishInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamPublishInput instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamPublishInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamPublishInput($$parsedSource as Partial<StreamPublishInput>);
    }
}

export class StreamPublishOutput {
    "ok": boolean;
    "mode"?: string;
    "channel"?: string;
    "frame_bytes"?: number;
    "error"?: string;

    /** Creates a new StreamPublishOutput instance. */
    constructor($$source: Partial<StreamPublishOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamPublishOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamPublishOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamPublishOutput($$parsedSource as Partial<StreamPublishOutput>);
    }
}

export class StreamRecentInput {
    "channel"?: string;

    /** Creates a new StreamRecentInput instance. */
    constructor($$source: Partial<StreamRecentInput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamRecentInput instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamRecentInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StreamRecentInput($$parsedSource as Partial<StreamRecentInput>);
    }
}

export class StreamRecentOutput {
    "ok": boolean;
    "channel"?: string;
    "frames"?: StreamFrame[];
    "frame_count"?: number;
    "error"?: string;

    /** Creates a new StreamRecentOutput instance. */
    constructor($$source: Partial<StreamRecentOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamRecentOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamRecentOutput {
        const $$createField2_0 = $$createType45;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("frames" in $$parsedSource) {
            $$parsedSource["frames"] = $$createField2_0($$parsedSource["frames"]);
        }
        return new StreamRecentOutput($$parsedSource as Partial<StreamRecentOutput>);
    }
}

export class StreamStatus {
    "ok": boolean;
    "running"?: boolean;
    "peer_count"?: number;
    "channel_count"?: number;
    "subscriber_counts"?: { [_ in string]?: number };
    "config"?: StreamConfig;
    "error"?: string;

    /** Creates a new StreamStatus instance. */
    constructor($$source: Partial<StreamStatus> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StreamStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): StreamStatus {
        const $$createField4_0 = $$createType18;
        const $$createField5_0 = $$createType46;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("subscriber_counts" in $$parsedSource) {
            $$parsedSource["subscriber_counts"] = $$createField4_0($$parsedSource["subscriber_counts"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField5_0($$parsedSource["config"]);
        }
        return new StreamStatus($$parsedSource as Partial<StreamStatus>);
    }
}

/**
 * TIMRuntimeOutput is the result of container.runtime.detect — one of
 * "" (none), "apple", "docker", "podman".
 */
export class TIMRuntimeOutput {
    "runtime": string;

    /** Creates a new TIMRuntimeOutput instance. */
    constructor($$source: Partial<TIMRuntimeOutput> = {}) {
        if (!("runtime" in $$source)) {
            this["runtime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TIMRuntimeOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): TIMRuntimeOutput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TIMRuntimeOutput($$parsedSource as Partial<TIMRuntimeOutput>);
    }
}

/**
 * TIMStateOutput mirrors the gui container TIMState. Field shape
 * matches the JSON the existing /dev/tim panel binds to so the
 * template needs no changes.
 */
export class TIMStateOutput {
    "name"?: string;
    "image"?: string;
    "runtime"?: string;
    "status"?: string;
    "started_at"?: string;
    "command"?: string[];
    "data_dir"?: string;

    /** Creates a new TIMStateOutput instance. */
    constructor($$source: Partial<TIMStateOutput> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TIMStateOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): TIMStateOutput {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("command" in $$parsedSource) {
            $$parsedSource["command"] = $$createField5_0($$parsedSource["command"]);
        }
        return new TIMStateOutput($$parsedSource as Partial<TIMStateOutput>);
    }
}

export class WailsLintCatalogEntry {
    "name": string;
    "description"?: string;
    "installed"?: boolean;

    /** Creates a new WailsLintCatalogEntry instance. */
    constructor($$source: Partial<WailsLintCatalogEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsLintCatalogEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): WailsLintCatalogEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WailsLintCatalogEntry($$parsedSource as Partial<WailsLintCatalogEntry>);
    }
}

export class WailsLintCatalogOutput {
    "ok": boolean;
    "tools"?: WailsLintCatalogEntry[];
    "error"?: string;

    /** Creates a new WailsLintCatalogOutput instance. */
    constructor($$source: Partial<WailsLintCatalogOutput> = {}) {
        if (!("ok" in $$source)) {
            this["ok"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsLintCatalogOutput instance from a string or object.
     */
    static createFrom($$source: any = {}): WailsLintCatalogOutput {
        const $$createField1_0 = $$createType48;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tools" in $$parsedSource) {
            $$parsedSource["tools"] = $$createField1_0($$parsedSource["tools"]);
        }
        return new WailsLintCatalogOutput($$parsedSource as Partial<WailsLintCatalogOutput>);
    }
}

export class WailsLintRunInput {
    "path": string;

    /** Creates a new WailsLintRunInput instance. */
    constructor($$source: Partial<WailsLintRunInput> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WailsLintRunInput instance from a string or object.
     */
    static createFrom($$source: any = {}): WailsLintRunInput {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WailsLintRunInput($$parsedSource as Partial<WailsLintRunInput>);
    }
}

export class chatBridgeToolCall {
    "name": string;
    "arguments"?: { [_ in string]?: any };

    /** Creates a new chatBridgeToolCall instance. */
    constructor($$source: Partial<chatBridgeToolCall> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new chatBridgeToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): chatBridgeToolCall {
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("arguments" in $$parsedSource) {
            $$parsedSource["arguments"] = $$createField1_0($$parsedSource["arguments"]);
        }
        return new chatBridgeToolCall($$parsedSource as Partial<chatBridgeToolCall>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ChatMessageOutput.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ChatConversationDetail.createFrom;
const $$createType4 = ChatConversationOutput.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ChatModelOutput.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = DevopsPlaybookEntry.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = DevopsScanFinding.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = DirEntry.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = GitEntry.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = LintIssue.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = $Create.Map($Create.Any, $Create.Any);
const $$createType19 = MemoryEntry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = MemorySearchHit.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $Create.Map($Create.Any, $Create.Any);
const $$createType24 = P2PPeer.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = ProcessListEntry.createFrom;
const $$createType27 = $Create.Array($$createType26);
const $$createType28 = RepoEntry.createFrom;
const $$createType29 = $Create.Array($$createType28);
const $$createType30 = SearchMatch.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = ActiveSession.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = SessionSummary.createFrom;
const $$createType35 = $Create.Array($$createType34);
const $$createType36 = SessionProject.createFrom;
const $$createType37 = $Create.Array($$createType36);
const $$createType38 = SessionSearchHit.createFrom;
const $$createType39 = $Create.Array($$createType38);
const $$createType40 = SessionTailLiveEvent.createFrom;
const $$createType41 = $Create.Array($$createType40);
const $$createType42 = StreamChannel.createFrom;
const $$createType43 = $Create.Array($$createType42);
const $$createType44 = StreamFrame.createFrom;
const $$createType45 = $Create.Array($$createType44);
const $$createType46 = StreamConfig.createFrom;
const $$createType47 = WailsLintCatalogEntry.createFrom;
const $$createType48 = $Create.Array($$createType47);
