// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * p2pBridge exposes the gui p2p service to the Wails frontend with
 * typed methods so the /dev/p2p panel can call State / Publish at
 * goroutine line-speed instead of HTTP-bridging through MCP.
 * 
 * First panel migrated off callBridge as part of the wails-binding
 * sweep (TODO(snider/wails) markers across ~20 panels). Pattern that
 * every other panel will follow:
 * 
 *   1. struct {core *core.Core} stored in pkg/server
 *   2. typed methods that wrap c.Action(...) and unwrap Result
 *   3. registered in cmd/core-ide/wails_boot.go via app.RegisterService
 *   4. wails3 generate bindings emits the matching TS into
 *      frontend/bindings/dappco.re/go/ide/pkg/server/p2pbridge.ts
 *   5. panel imports + calls the typed binding instead of callBridge
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Publish sends a typed envelope through the gui p2p router. Returns
 * success=false silently when no transport is configured (matches the
 * /dev/p2p panel's "no listener bound" empty-state UX).
 */
export function Publish(input: $models.P2PPublishInput): $CancellablePromise<$models.P2PPublishOutput> {
    return $Call.ByID(1361524914, input).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * State queries the live p2p service for node id, listen address, and
 * connected peer list. Returns an empty payload when the bridge has no
 * core attached (test fallback) — the panel surfaces that as the
 * "no listener bound" empty state via its own logic.
 */
export function State(): $CancellablePromise<$models.P2PStateOutput> {
    return $Call.ByID(1603463940).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.P2PPublishOutput.createFrom;
const $$createType1 = $models.P2PStateOutput.createFrom;
