// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * phpBridge — typed wails wrapper over MCPBridge php_* tools (Laravel
 * project discovery + composer/artisan runner).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Detect(): $CancellablePromise<$models.PHPDetectOutput> {
    return $Call.ByID(2389393330).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Project(input: $models.PHPProjectInput): $CancellablePromise<$models.PHPProjectOutput> {
    return $Call.ByID(99372894, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Run(input: $models.PHPRunInput): $CancellablePromise<$models.PHPRunOutput> {
    return $Call.ByID(2696412010, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Scripts(input: $models.PHPProjectInput): $CancellablePromise<$models.PHPScriptsOutput> {
    return $Call.ByID(1451184955, input).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.PHPDetectOutput.createFrom;
const $$createType1 = $models.PHPProjectOutput.createFrom;
const $$createType2 = $models.PHPRunOutput.createFrom;
const $$createType3 = $models.PHPScriptsOutput.createFrom;
