// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * reposBridge — typed wails wrapper over MCPBridge repos_status tool.
 * /dev/repos is the multi-repo dashboard; cache TTL 30s server-side
 * because git status across N roots is the slowest scan in the IDE.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Status scans every configured root for git state. Empty Roots →
 * the bridge falls back to the canonical Lethean roots baked into
 * the server.
 */
export function Status(input: $models.ReposStatusInput): $CancellablePromise<$models.ReposStatusOutput> {
    return $Call.ByID(1563948512, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ReposStatusOutput.createFrom;
