// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * searchBridge — typed wails wrapper over the existing MCPBridge
 * workspace_search tool. Hot path for the IDE; every keystroke in
 * /dev/search runs the ripgrep dispatcher.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Search runs ripgrep across the workspace and returns matches. Empty
 * matches with OK=true is the canonical "found nothing" signal.
 */
export function Search(input: $models.SearchInput): $CancellablePromise<$models.SearchOutput> {
    return $Call.ByID(3194052285, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SearchOutput.createFrom;
