// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * sessionBridge — typed wails wrapper over MCPBridge session_* tools.
 * /dev/sessions has the heaviest tool surface in the IDE: project
 * list (cached), per-project session list, inspect, active scan,
 * cross-session search, live tail.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Active(input: $models.SessionActiveInput): $CancellablePromise<$models.SessionActiveOutput> {
    return $Call.ByID(3146692779, input).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Inspect returns the typed map directly via a passthrough — analytics
 * + event_tail are nested + variable-shape, so we route through JSON
 * and let the FE bind the wails-emitted model.
 */
export function Inspect(input: $models.SessionInspectInput): $CancellablePromise<{ [_ in string]?: any }> {
    return $Call.ByID(1040948859, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function List(input: $models.SessionListInput): $CancellablePromise<$models.SessionListOutput> {
    return $Call.ByID(3489560437, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ProjectsList(input: $models.SessionProjectsInput): $CancellablePromise<$models.SessionProjectsOutput> {
    return $Call.ByID(3763267563, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function Search(input: $models.SessionSearchInput): $CancellablePromise<$models.SessionSearchOutput> {
    return $Call.ByID(1146328117, input).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Tail(input: $models.SessionTailInput): $CancellablePromise<$models.SessionTailOutput> {
    return $Call.ByID(4054213271, input).then(($result: any) => {
        return $$createType5($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SessionActiveOutput.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $models.SessionListOutput.createFrom;
const $$createType3 = $models.SessionProjectsOutput.createFrom;
const $$createType4 = $models.SessionSearchOutput.createFrom;
const $$createType5 = $models.SessionTailOutput.createFrom;
