// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * streamBridge — typed wails wrapper over MCPBridge stream_* tools.
 * Inspector for the in-process go-stream Hub the IDE auto-publishes
 * every core ACTION onto (post-#300).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Channels(): $CancellablePromise<$models.StreamChannelsOutput> {
    return $Call.ByID(1258819533).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Publish(input: $models.StreamPublishInput): $CancellablePromise<$models.StreamPublishOutput> {
    return $Call.ByID(891120128, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Recent(input: $models.StreamRecentInput): $CancellablePromise<$models.StreamRecentOutput> {
    return $Call.ByID(966695942, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Status(): $CancellablePromise<$models.StreamStatus> {
    return $Call.ByID(1054938727).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = $models.StreamChannelsOutput.createFrom;
const $$createType1 = $models.StreamPublishOutput.createFrom;
const $$createType2 = $models.StreamRecentOutput.createFrom;
const $$createType3 = $models.StreamStatus.createFrom;
