// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * tenantBridge — typed wails wrapper over MCPBridge tenant_* tools
 * (multi-tenancy + entitlements over core/go-tenant).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Can(input: $models.TenantCanInput): $CancellablePromise<$models.TenantCanOutput> {
    return $Call.ByID(1434748085, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Status(): $CancellablePromise<$models.TenantStatusOutput> {
    return $Call.ByID(220985599).then(($result: any) => {
        return $$createType1($result);
    });
}

export function User(input: $models.TenantUserInput): $CancellablePromise<$models.TenantPayloadOutput> {
    return $Call.ByID(1218302402, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function Workspace(input: $models.TenantWorkspaceInput): $CancellablePromise<$models.TenantPayloadOutput> {
    return $Call.ByID(4131212486, input).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TenantCanOutput.createFrom;
const $$createType1 = $models.TenantStatusOutput.createFrom;
const $$createType2 = $models.TenantPayloadOutput.createFrom;
