// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * terminalBridge — Wails bridge for the in-IDE terminal pane's control plane.
 * 
 * Bytes (keystroke firehose + PTY output) flow through the WebSocket endpoint
 * /terminal/ws/:sid on the MCPBridge — kept off the Wails JSON channel because
 * every keypress would spend a full JSON round-trip otherwise. The bridge
 * methods here are the small, infrequent control operations:
 * 
 *   - OpenSession  — allocate a PTY, return the session ID
 *   - CloseSession — kill a session by ID
 *   - Resize       — push window cols/rows to the PTY (called on layout changes)
 *   - ListSessions — enumerate live sessions for a future tab strip
 * 
 * WriteInput is exposed too as a fallback for when the WebSocket isn't an
 * option (e.g. a synthetic keypress from a script). Production xterm.js uses
 * the WS path.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CloseSession kills the session by ID. No-op if the ID is unknown.
 */
export function CloseSession(id: string): $CancellablePromise<$models.TerminalActionResult> {
    return $Call.ByID(1774360045, id).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListSessions returns metadata for all live sessions (used by future tab
 * strip / multi-session UI).
 */
export function ListSessions(): $CancellablePromise<$models.TerminalSessionsResult> {
    return $Call.ByID(939819504).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * OpenSession allocates a new PTY-backed session. Returns the session ID and
 * a relative WebSocket URL the FE should dial for the byte stream.
 */
export function OpenSession(input: $models.TerminalOpenInput): $CancellablePromise<$models.TerminalOpenResult> {
    return $Call.ByID(918311467, input).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * Resize pushes new cols/rows to the PTY. Called on container resize (xterm
 * fit-addon) or explicit user actions.
 */
export function Resize(id: string, cols: number, rows: number): $CancellablePromise<$models.TerminalActionResult> {
    return $Call.ByID(553083425, id, cols, rows).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * WriteInput is a fallback control-plane input path (the production keystroke
 * stream goes through the WS). Useful for synthetic input from scripts /
 * tests / Cladius "type this command for me" flows.
 */
export function WriteInput(id: string, data: string): $CancellablePromise<$models.TerminalActionResult> {
    return $Call.ByID(2556589488, id, data).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TerminalActionResult.createFrom;
const $$createType1 = $models.TerminalSessionsResult.createFrom;
const $$createType2 = $models.TerminalOpenResult.createFrom;
