// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * timBridge surfaces the gui container service's TIM (Trusted In-
 * Memory) container manager actions to the Wails frontend with typed
 * methods so /dev/tim can call DetectRuntime / Status / Start / Stop
 * at goroutine line-speed.
 * 
 * Second panel migrated off callBridge as part of the wails-binding
 * sweep — same pattern as p2pBridge.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DetectRuntime probes the host for an isolated workload runtime in
 * preference order: Apple Containers > Docker > Podman > none. Used
 * by the panel's "Runtime" card to surface either the live runtime
 * or the "no runtime detected" empty state.
 */
export function DetectRuntime(): $CancellablePromise<$models.TIMRuntimeOutput> {
    return $Call.ByID(3574472604).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * Start launches the configured TIM container. Returns the new state
 * post-start so the panel can re-bind without a separate refresh
 * round-trip.
 */
export function Start(): $CancellablePromise<$models.TIMStateOutput> {
    return $Call.ByID(3006459365).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Status reads the current TIM container state — image / name / status
 * / start time. Empty string fields surface as the panel's "not
 * configured" / "stopped" empty states (no toast errors for "TIM not
 * running").
 */
export function Status(): $CancellablePromise<$models.TIMStateOutput> {
    return $Call.ByID(885929305).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Stop tears down the running TIM container. Like Start, returns the
 * post-op state.
 */
export function Stop(): $CancellablePromise<$models.TIMStateOutput> {
    return $Call.ByID(2109051575).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.TIMRuntimeOutput.createFrom;
const $$createType1 = $models.TIMStateOutput.createFrom;
