// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * updatesBridge — typed wails wrapper over MCPBridge updates_* +
 * selfupdate_* tools (tool version tracking + core-ide self-update).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Refresh(input: $models.UpdatesRefreshInput): $CancellablePromise<$models.UpdatesRefreshOutput> {
    return $Call.ByID(3047022706, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SelfUpdateApply(): $CancellablePromise<$models.SelfUpdateApplyOutput> {
    return $Call.ByID(2854403348).then(($result: any) => {
        return $$createType1($result);
    });
}

export function SelfUpdateStatus(): $CancellablePromise<$models.SelfUpdateStatusOutput> {
    return $Call.ByID(2235926082).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.UpdatesRefreshOutput.createFrom;
const $$createType1 = $models.SelfUpdateApplyOutput.createFrom;
const $$createType2 = $models.SelfUpdateStatusOutput.createFrom;
