// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * viBridge exposes the vi.Service to the Wails frontend. Methods here generate
 * TypeScript bindings the Angular Vi Control Panel calls — Status / Briefs /
 * Sites / Activity. Per the desktop convergence RFC §1.3, "expect data to come
 * from the Go side via Wails bindings."
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as vi$0 from "../vi/models.js";

/**
 * Activity returns the activity feed — Vi's narration interleaved with the
 * operator's recent actions.
 * 
 * 	const activity = await ViBridge.Activity();
 */
export function Activity(): $CancellablePromise<vi$0.ActivityItem[]> {
    return $Call.ByID(3540328295).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * Briefs returns the current brief feed — what Vi has surfaced for attention.
 * 
 * 	const briefs = await ViBridge.Briefs();
 */
export function Briefs(): $CancellablePromise<vi$0.Brief[]> {
    return $Call.ByID(3186532115).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * Sites returns the watched-site list with status / uptime / response.
 * 
 * 	const sites = await ViBridge.Sites();
 */
export function Sites(): $CancellablePromise<vi$0.Site[]> {
    return $Call.ByID(4227738542).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * Status returns the live Vi presence state (connected, latency, watching, pending).
 * 
 * 	const status = await ViBridge.Status();
 */
export function Status(): $CancellablePromise<vi$0.ViStatus> {
    return $Call.ByID(2745752964).then(($result: any) => {
        return $$createType6($result);
    });
}

// Private type creation functions
const $$createType0 = vi$0.ActivityItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = vi$0.Brief.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = vi$0.Site.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = vi$0.ViStatus.createFrom;
