// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * windowBridge — typed wails wrapper over MCPBridge window_* tools.
 * 
 * The window surface IS the application-framework primitive in CoreIDE.
 * Plugins (CoreAgent, Lem.Lab, etc.) mount as named windows and the IDE
 * drives them identically — open, position, focus, query state. This
 * bridge gives plugins (and panels) a typed entry-point with no
 * callBridge round-trip.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AlwaysOnTop(input: $models.WindowAlwaysOnTopInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(497880056, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Bounds(input: $models.WindowSetBoundsInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(2138184388, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Center(input: $models.WindowNameInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(649224432, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Close(input: $models.WindowNameInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(4144001103, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Focus(input: $models.WindowNameInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(1484999551, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Focused(input: $models.WindowNameInput): $CancellablePromise<$models.WindowFocusedOutput> {
    return $Call.ByID(3990328382, input).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Fullscreen(input: $models.WindowFullscreenInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(2367817596, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Get(input: $models.WindowNameInput): $CancellablePromise<$models.WindowInfoOutput> {
    return $Call.ByID(887147379, input).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetTitle(input: $models.WindowNameInput): $CancellablePromise<$models.WindowTitleOutput> {
    return $Call.ByID(2992349475, input).then(($result: any) => {
        return $$createType3($result);
    });
}

export function List(): $CancellablePromise<$models.WindowListOutput> {
    return $Call.ByID(1173064685).then(($result: any) => {
        return $$createType4($result);
    });
}

export function Maximise(input: $models.WindowNameInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(3014463102, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Minimise(input: $models.WindowNameInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(1308330748, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Open(input: $models.WindowOpenInput): $CancellablePromise<$models.WindowOpenOutput> {
    return $Call.ByID(2705885293, input).then(($result: any) => {
        return $$createType5($result);
    });
}

export function Position(input: $models.WindowSetPositionInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(3760005318, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Restore(input: $models.WindowNameInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(1811185493, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function SetTitle(input: $models.WindowSetTitleInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(1010669711, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Size(input: $models.WindowSetSizeInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(282228560, input).then(($result: any) => {
        return $$createType0($result);
    });
}

export function Visibility(input: $models.WindowVisibilityInput): $CancellablePromise<$models.WindowMutationOutput> {
    return $Call.ByID(2647473289, input).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.WindowMutationOutput.createFrom;
const $$createType1 = $models.WindowFocusedOutput.createFrom;
const $$createType2 = $models.WindowInfoOutput.createFrom;
const $$createType3 = $models.WindowTitleOutput.createFrom;
const $$createType4 = $models.WindowListOutput.createFrom;
const $$createType5 = $models.WindowOpenOutput.createFrom;
