// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ActivityItem is one row in the activity feed. Who = "vi" or "you" — the
 * mono badge in the UI uses the literal strings.
 */
export class ActivityItem {
    /**
     * "vi" | "you"
     */
    "who": string;
    "time": string;
    "text": string;

    /**
     * e.g. "wave-pulse", "shield-check"
     */
    "icon": string;
    "tone": Tone;

    /** Creates a new ActivityItem instance. */
    constructor($$source: Partial<ActivityItem> = {}) {
        if (!("who" in $$source)) {
            this["who"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("tone" in $$source)) {
            this["tone"] = Tone.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ActivityItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityItem($$parsedSource as Partial<ActivityItem>);
    }
}

/**
 * Brief is one card in the brief feed. Vi surfaces what matters; the body
 * reads in the chill-chick-raven character voice — calm, factual, with the
 * "what to do next" implied rather than demanded.
 */
export class Brief {
    "tone": Tone;

    /**
     * ISO or human ("06:42", "Yesterday")
     */
    "time": string;
    "title": string;
    "body": string;
    "actions": BriefAction[];
    "done"?: boolean;

    /**
     * Darwin/iPad only ("⌘1")
     */
    "shortcut"?: string;

    /** Creates a new Brief instance. */
    constructor($$source: Partial<Brief> = {}) {
        if (!("tone" in $$source)) {
            this["tone"] = Tone.$zero;
        }
        if (!("time" in $$source)) {
            this["time"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            this["body"] = "";
        }
        if (!("actions" in $$source)) {
            this["actions"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Brief instance from a string or object.
     */
    static createFrom($$source: any = {}): Brief {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField4_0($$parsedSource["actions"]);
        }
        return new Brief($$parsedSource as Partial<Brief>);
    }
}

/**
 * BriefAction is one of the buttons offered on a Brief card. Primary actions
 * render with the brand-tinted button; secondary as outlined.
 */
export class BriefAction {
    "label": string;
    "primary"?: boolean;

    /** Creates a new BriefAction instance. */
    constructor($$source: Partial<BriefAction> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BriefAction instance from a string or object.
     */
    static createFrom($$source: any = {}): BriefAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BriefAction($$parsedSource as Partial<BriefAction>);
    }
}

/**
 * Site is one watched site row. Mono numbers (uptime, response, deploy time)
 * per the native handoff.
 */
export class Site {
    "domain": string;
    "stack": string;
    "status": SiteStatus;

    /**
     * e.g. "99.998"
     */
    "uptime": string;

    /**
     * ms
     */
    "response": number;

    /**
     * 12 points
     */
    "sparkData": number[];

    /**
     * human relative
     */
    "lastDeploy": string;
    "warn"?: string;

    /** Creates a new Site instance. */
    constructor($$source: Partial<Site> = {}) {
        if (!("domain" in $$source)) {
            this["domain"] = "";
        }
        if (!("stack" in $$source)) {
            this["stack"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = SiteStatus.$zero;
        }
        if (!("uptime" in $$source)) {
            this["uptime"] = "";
        }
        if (!("response" in $$source)) {
            this["response"] = 0;
        }
        if (!("sparkData" in $$source)) {
            this["sparkData"] = [];
        }
        if (!("lastDeploy" in $$source)) {
            this["lastDeploy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Site instance from a string or object.
     */
    static createFrom($$source: any = {}): Site {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sparkData" in $$parsedSource) {
            $$parsedSource["sparkData"] = $$createField5_0($$parsedSource["sparkData"]);
        }
        return new Site($$parsedSource as Partial<Site>);
    }
}

/**
 * SiteStatus is the at-a-glance health of a watched site.
 */
export enum SiteStatus {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusGreen = "green",
    StatusAmber = "amber",
    StatusRed = "red",
};

/**
 * Tone categorises a brief or activity row by severity. Mirrors the TS union
 * `'warning' | 'success' | 'info' | 'neutral' | 'danger'`.
 */
export enum Tone {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ToneWarning = "warning",
    ToneSuccess = "success",
    ToneInfo = "info",
    ToneNeutral = "neutral",
    ToneDanger = "danger",
};

/**
 * ViStatus is the live status pinned in the sidebar + status bar — Vi
 * connected indicator, latency, what she's watching, and what's pending
 * the user's attention.
 */
export class ViStatus {
    "connected": boolean;
    "latencyMs": number;
    "watching": number;
    "pending": number;

    /** Creates a new ViStatus instance. */
    constructor($$source: Partial<ViStatus> = {}) {
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }
        if (!("latencyMs" in $$source)) {
            this["latencyMs"] = 0;
        }
        if (!("watching" in $$source)) {
            this["watching"] = 0;
        }
        if (!("pending" in $$source)) {
            this["pending"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ViStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ViStatus($$parsedSource as Partial<ViStatus>);
    }
}

// Private type creation functions
const $$createType0 = BriefAction.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
