// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ActivityItem is one row in the activity feed. Who = "vi" or "you" — the
 * mono badge in the UI uses the literal strings.
 */
export class ActivityItem {
    /**
     * Creates a new ActivityItem instance.
     * @param {Partial<ActivityItem>} [$$source = {}] - The source object to create the ActivityItem.
     */
    constructor($$source = {}) {
        if (!("who" in $$source)) {
            /**
             * "vi" | "you"
             * @member
             * @type {string}
             */
            this["who"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["text"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * e.g. "wave-pulse", "shield-check"
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("tone" in $$source)) {
            /**
             * @member
             * @type {Tone}
             */
            this["tone"] = Tone.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActivityItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActivityItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ActivityItem(/** @type {Partial<ActivityItem>} */($$parsedSource));
    }
}

/**
 * Brief is one card in the brief feed. Vi surfaces what matters; the body
 * reads in the chill-chick-raven character voice — calm, factual, with the
 * "what to do next" implied rather than demanded.
 */
export class Brief {
    /**
     * Creates a new Brief instance.
     * @param {Partial<Brief>} [$$source = {}] - The source object to create the Brief.
     */
    constructor($$source = {}) {
        if (!("tone" in $$source)) {
            /**
             * @member
             * @type {Tone}
             */
            this["tone"] = Tone.$zero;
        }
        if (!("time" in $$source)) {
            /**
             * ISO or human ("06:42", "Yesterday")
             * @member
             * @type {string}
             */
            this["time"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (!("actions" in $$source)) {
            /**
             * @member
             * @type {BriefAction[]}
             */
            this["actions"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["done"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Darwin/iPad only ("⌘1")
             * @member
             * @type {string | undefined}
             */
            this["shortcut"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Brief instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Brief}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("actions" in $$parsedSource) {
            $$parsedSource["actions"] = $$createField4_0($$parsedSource["actions"]);
        }
        return new Brief(/** @type {Partial<Brief>} */($$parsedSource));
    }
}

/**
 * BriefAction is one of the buttons offered on a Brief card. Primary actions
 * render with the brand-tinted button; secondary as outlined.
 */
export class BriefAction {
    /**
     * Creates a new BriefAction instance.
     * @param {Partial<BriefAction>} [$$source = {}] - The source object to create the BriefAction.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["primary"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BriefAction instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BriefAction}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BriefAction(/** @type {Partial<BriefAction>} */($$parsedSource));
    }
}

/**
 * Site is one watched site row. Mono numbers (uptime, response, deploy time)
 * per the native handoff.
 */
export class Site {
    /**
     * Creates a new Site instance.
     * @param {Partial<Site>} [$$source = {}] - The source object to create the Site.
     */
    constructor($$source = {}) {
        if (!("domain" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["domain"] = "";
        }
        if (!("stack" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["stack"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {SiteStatus}
             */
            this["status"] = SiteStatus.$zero;
        }
        if (!("uptime" in $$source)) {
            /**
             * e.g. "99.998"
             * @member
             * @type {string}
             */
            this["uptime"] = "";
        }
        if (!("response" in $$source)) {
            /**
             * ms
             * @member
             * @type {number}
             */
            this["response"] = 0;
        }
        if (!("sparkData" in $$source)) {
            /**
             * 12 points
             * @member
             * @type {number[]}
             */
            this["sparkData"] = [];
        }
        if (!("lastDeploy" in $$source)) {
            /**
             * human relative
             * @member
             * @type {string}
             */
            this["lastDeploy"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["warn"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Site instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Site}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sparkData" in $$parsedSource) {
            $$parsedSource["sparkData"] = $$createField5_0($$parsedSource["sparkData"]);
        }
        return new Site(/** @type {Partial<Site>} */($$parsedSource));
    }
}

/**
 * SiteStatus is the at-a-glance health of a watched site.
 * @readonly
 * @enum {string}
 */
export const SiteStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusGreen: "green",
    StatusAmber: "amber",
    StatusRed: "red",
};

/**
 * Tone categorises a brief or activity row by severity. Mirrors the TS union
 * `'warning' | 'success' | 'info' | 'neutral' | 'danger'`.
 * @readonly
 * @enum {string}
 */
export const Tone = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ToneWarning: "warning",
    ToneSuccess: "success",
    ToneInfo: "info",
    ToneNeutral: "neutral",
    ToneDanger: "danger",
};

/**
 * ViStatus is the live status pinned in the sidebar + status bar — Vi
 * connected indicator, latency, what she's watching, and what's pending
 * the user's attention.
 */
export class ViStatus {
    /**
     * Creates a new ViStatus instance.
     * @param {Partial<ViStatus>} [$$source = {}] - The source object to create the ViStatus.
     */
    constructor($$source = {}) {
        if (!("connected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["connected"] = false;
        }
        if (!("latencyMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latencyMs"] = 0;
        }
        if (!("watching" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["watching"] = 0;
        }
        if (!("pending" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ViStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ViStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ViStatus(/** @type {Partial<ViStatus>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = BriefAction.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
